### ISSUE TITLE
Error on starting web server

### ISSUE THREAD

**Issue by binlijin** [mistercrunch/panoramix#14]
Hi,
I'm trying to install Panoramix.
Server is Mac 10.9.5 and Phyton version is 2.7.5
After installation I've first  start  web server and meet with error as follows：
```
$ python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/Users/tianzhao/dev/apache/panoramix/app/__init__.py", line 2, in <module>
    from flask import Flask
ImportError: No module named flask
```

**Comment by binlijin** [comment]
ok, it my python's problem, Flask not install sys.path, and can not find it.

**Comment by mistercrunch** [comment]
I think you may have skipped the installation part that goes
`pip install -r requirements.txt`

This should install all requirements including `flask`.

**Comment by binlijin** [comment]
hi mistercrunch, i do run the pip command to install all requirements including flask, but all modules install in /usr/local/lib/python2.7/site-packages, and i add the path to python's sys.path and it works now.
```
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
```

**Comment by mistercrunch** [comment]
Weird, normally `site-packages` is included in your Python path automatically, unless there are many python installs that don't play well together...

**Comment by chejinye** [comment]
@binlijin  你知道直接下载code 怎么在自己的pycharm里面启动吗

**Comment by binlijin** [comment]
@chejinye 我不熟悉，之前我只是试用这个ui看满不满足我们的需求。

**Comment by chejinye** [comment]
@binlijin 那你们最后用了这个东西吗
