### ISSUE TITLE
Multiple refresh events when having multiple filters

### ISSUE THREAD

**Issue by gbrian** [mistercrunch/panoramix#170]
I guess there's an error when managing multiple filters. So I'll move **slice.setFilter** out from the loop, don't you?

![image](https://cloud.githubusercontent.com/assets/767180/13578548/e14f9aac-e498-11e5-9b09-920330a72d2e.png)

**Comment by mistercrunch** [comment]
Good catch, yeah it should really just set the filter that has changed, I'm going to push a fix.

**Comment by gbrian** [comment]
Many thanks, 
I still setting up dev environment and playing around. 
Next time I'll try to create a PR.
