### ISSUE TITLE
Query component: limit_spec is not valid for query type: groupBy.The list of valid

### ISSUE THREAD

**Issue by nihed** [mistercrunch/panoramix#4]
Hi, 
When I try to check my datasource 

ValueError
ValueError: Query component: limit_spec is not valid for query type: groupBy.The list of valid components is: 
 ['datasource', 'granularity', 'filter', 'aggregations', 'post_aggregations', 'intervals', 'dimensions']

**Comment by mistercrunch** [comment]
Did you install the trunk version of `pydruid` as specified in my [revised] installation instructions?

```
# I needed a feature added to pydruid, and it got merged into their 
# master branch but isn't on pypi yet, so you'll need the latest.
git clone https://github.com/metamx/pydruid.git
cd pydruid
python setup.py install
```

**Comment by mistercrunch** [comment]
here's the related commit I wrote to add the feature (merged into master, but not on pypi):
https://github.com/metamx/pydruid/commit/97397d3ca84e1f9903752f04c06ad0375d5767c1

**Comment by nihed** [comment]
works for me now, thank you

**Comment by syedbarimanjan** [comment]
Hi I would like to work on this.
