### ISSUE TITLE
Exception occurred when pip install panoramix

### ISSUE THREAD

**Issue by wangmuling** [mistercrunch/panoramix#47]
when I pip install panoramix,I got some exceptions:

   Installing collected packages: panoramix
  Running setup.py install for panoramix
    changing mode of build/scripts-2.6/panoramix from 644 to 755
    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/panoramix/forms.py', 206, 52, "        field_css_classes = {k: ['form-control'] for k in px_form_fields.keys()}\n"))
    
    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/panoramix/viz.py', 57, 15, '            for k in form_data.keys()\n'))
    
    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/panoramix/models.py', 361, 40, '        cols = {col.column_name: col for col in self.columns}\n'))
    
    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/panoramix/views.py', 401, 40, "                int(o['slice_id']):o for o in json.loads(dashboard.position_json)}\n"))
    
    changing mode of /usr/bin/panoramix to 755

And what's you advise here?Thanks

**Comment by mistercrunch** [comment]
Can you try with python2.7?

**Comment by mistercrunch** [comment]
I added a note in the README about python version support. We're adding in python 3 support soon, no one should be using 2.6 anymore.
