### ISSUE TITLE
Change port to default values

### ISSUE THREAD

**Issue by nihed** [mistercrunch/panoramix#5]
Hi, 
If it's possible to change config with default port used by druid 

Actual values : 
ROW_LIMIT = 5000

DRUID_HOST = '0.0.0.0'
DRUID_PORT = 8080
DRUID_BASE_ENDPOINT = 'druid/v2'

COORDINATOR_HOST = '0.0.0.0'
COORDINATOR_PORT = '8080'
COORDINATOR_BASE_ENDPOINT = 'druid/coordinator/v1'

New values : 

ROW_LIMIT = 5000

DRUID_HOST = '0.0.0.0'
DRUID_PORT = '8084'
DRUID_BASE_ENDPOINT = 'druid/v2'

COORDINATOR_HOST = '0.0.0.0'
COORDINATOR_PORT = '8081'
COORDINATOR_BASE_ENDPOINT = 'druid/coordinator/v1'

based on this documentation : http://druid.io/docs/0.8.0/tutorials/tutorial-the-druid-cluster.html

**Comment by mistercrunch** [comment]
Thanks for the feedback, I'm now using the default ports as you specified:
https://github.com/mistercrunch/panoramix/commit/fbc74244d4b92c243503e2375725676e64eb9b21
