### ISSUE TITLE
How can I specify the timezone in panoramix

### ISSUE THREAD

**Issue by wangmuling** [mistercrunch/panoramix#50]
Hi,
  when I used the panoramix ,I have a trouble in the timezone.If the panoramix can support other timezones besides UTC?And How can I specify the timezone,such as "Asia/ShangHai"

And  what's you advice here?Thanks!

**Comment by mistercrunch** [comment]
It's not possible just yet, but I was thinking that we could add dataset metadata to pick between data time or local time or maybe specify an offset.

**Comment by wangmuling** [comment]
Should I modify the panoramix code?Or How can I specify the offset.My all druid sources are ingesting with "Asia/Shanghai" timezone .Thanks!

**Comment by mistercrunch** [comment]
I can add the feature this week. In the meantime you'll have to apply the offset in your head :)
