### ISSUE TITLE
the search intervals time is not accuracy

### ISSUE THREAD

**Issue by 492066199** [mistercrunch/panoramix#57]
hi. dear

the since text that I fill it with -1,but the intervals beginning time is 01:00:00,it must be 2015-11-06T17:27:51+00:00.is this something wrong with me?

"intervals": "2015-11-06T01:00:00+00:00/2015-11-06T18:27:51+00:00",

**Comment by mistercrunch** [comment]
The `since` input box expects either hard coded or intervals in human language ("1 day ago", "2015", "2015-04-01", "3 hours ago", ...). I use 2 libraries to do this and I'm guessing "-1" gets interpreted as "1AM of the current day", which isn't a bad guess.

**Comment by 492066199** [comment]
thank you!  I use "9 hours ago ",it works well.
