### ISSUE TITLE
run.py use port=8081

### ISSUE THREAD

**Issue by nihed** [mistercrunch/panoramix#6]
port used by run.py is the Coordinator default one. 

If it's possible to change to another one in case if someone test this application in the same server to the coordinator

**Comment by nihed** [comment]
By the way, I just discover that you define 8088 in documentation
http://localhost:8088, login using the credential you entered while creating the admin account, and

**Comment by mistercrunch** [comment]
addressed here as well:
https://github.com/mistercrunch/panoramix/commit/fbc74244d4b92c243503e2375725676e64eb9b21
