### ISSUE TITLE
Docker for panoramix

### ISSUE THREAD

**Issue by wbchn** [mistercrunch/panoramix#62]
We are trying using panoramix in docker, and I build a repo: https://github.com/wbchn/panoramix-docker .

But I found after `fabmanager create-admin`, the first admin could not login panoramix page, it told me password was wrong. Is there other way to auth, or setting a default user(could change password after login)?

**Comment by mistercrunch** [comment]
Please refer to the fab docs or ask the question on that repo:
http://flask-appbuilder.readthedocs.org/en/latest/

**Comment by gbrian** [comment]
Same issue,
Fixed by:
* re run **fabmanager create-admin --app panoramix** (but this time leave all defaults and only set password)

Now I can login with **admin** user

**Comment by wbchn** [comment]
@gbrian thank you, I will try later.

**Comment by gbrian** [comment]
Hi @wbchn, 
just re-installed (in a windows platform, sorry I'm testing different platforms)
this time I kept all defaults values except for password and worked fine, so maybe related with username...who knows ;).

Hope this helps.
Best regards

**Comment by wbchn** [comment]
@gbrian, I got the reason. Just setting `PYTHONPATH` before `fabmanager create-admin`, it will overwrite default config which setting `SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/caravel.db`.

My project(renamed from panoramix-docker): https://github.com/wbchn/caravel-docker

**Comment by philippfrenzel** [comment]
Hi, this docker works like charm, take a look into the docker-compose.yml

https://hub.docker.com/r/amancevice/caravel/

**Comment by wbchn** [comment]
@philippfrenzel  no docker for caravel(panoramix) last year, so i build this docker project.

`amancevice/caravel` is better, but it can not add admin automatic in first time, which we need auto-deploy to docker cluster or add to compose(we do not use it now).
